### ISSUE TITLE
Double computing function value in Newton iterations due to backtracking

### ISSUE THREAD

**Issue by KristofferC** [EconForge/NLsolve.jl#40]
Not all linesearches in `Optim` returns the computed function value. Instead we unnecessarily have to recompute it, even though we just evaluated the function at the same point. https://github.com/EconForge/NLsolve.jl/blob/ff78c8e1323c0038db8a95a20ce8250bf3b9f86b/src/newton.jl#L130

We should probably look into getting the backtracking functions in Optim return the function value and we can then skip a function evaluation for each newton iteration.

**Comment by spencerlyon2** [comment]
That'd be great. There really isn't a need for us to recompute here.
