### ISSUE TITLE
Add check in `nlsolve` to see if user passed in a solution and return immediately

### ISSUE THREAD

**Issue by spencerlyon2** [EconForge/NLsolve.jl#48]
Just a question. Do we want to do this? It would cost one function evaluation and would rarely happen, but would be nice when it does happen...

**Comment by KristofferC** [comment]
Could you explain why would it save a function evaluation? The way I see it, we could potentially save a gradient evaluation but at the cost of chaning a `fg!` call to two separate `f!` and `g!` calls.

**Comment by spencerlyon2** [comment]
I think that's right, it would save a gradient evaluation and the cost of running through the body of the Newton function once  (this part is probably negligible)

**Comment by KristofferC** [comment]
Personally I think it is a rare enough occurrence to call a solver with the correct solution that we don't have to think about it.

**Comment by spencerlyon2** [comment]
Sounds good.
