### ISSUE TITLE
minpack_results.dat getting changed by tests, resulting in dirty state

### ISSUE THREAD

**Issue by tkelman** [EconForge/NLsolve.jl#57]
Which prevents the package from being updated or removed by Pkg. Not good - this happens on PkgEval, and I can also get it to happen on Ubuntu 14.04. Here's what that file is looking like for me: https://gist.github.com/4e59d49d58852062664f6970bbb82b11

**Comment by KristofferC** [comment]
Yeah, thats bad and my fault. Will fix.

**Comment by KristofferC** [comment]
Fixed by #58
