### ISSUE TITLE
Recommended way of passing static parameters?

### ISSUE THREAD

**Issue by amellnik** [EconForge/NLsolve.jl#69]
I am solving a large number of similar functions of two variables, where the function is defined in terms of several constants that change between each call of `nlsolve`.  Is there any suggested method for passing these parameters to `nlsolve` without using metaprogramming to constantly redefine the function or defining them outside of the scope?

```julia
using NLsolve

function f!(x, fvec, c)
    fvec[1] = (x[1]+c[1])*(x[2]^3-7)+c[2]
    fvec[2] = sin(x[2]*exp(x[1])-c[3])
end

#It would be nice to do something like this?
nlsolve(f!, [ 0.1; 1.2], c = [1,2,18])

#This works, but looks really dodgy
function f2!(x, fvec)
    fvec[1] = (x[1]+c[1])*(x[2]^3-7)+c[2]
    fvec[2] = sin(x[2]*exp(x[1])-c[3])
end

c = [1,2,3]
nlsolve(f2!, [ 0.1; 1.2])
```

**Comment by KristofferC** [comment]
Use a closure.

```jl
f(x, parameter)  = x + parameter
function main()
    parameter = 3
    f_closure(x) = f(x, paramater)
    nlsolve(f_closure, [0.1; 1.2])
end
```

**Comment by amellnik** [comment]
@KristofferC -- that's exactly what I needed -- thanks!  I don't know if this merits a mention in the docs here, so I'll close.

**Comment by KristofferC** [comment]
Make sure the `parameter` is not declared in global scope but inside a function.
