### ISSUE TITLE
WARNING: slice is deprecated, use view instead.

### ISSUE THREAD

**Issue by jmarcellopereira** [EconForge/NLsolve.jl#73]
```
function sistema_NLS(x, função)
    função[1] = 3*x[1] + cos(x[2]) - 5    
    função[2] = -sin(x[1]) + x[2] - 2
end

solNLS = nlsolve(sistema_NLS, [ 1.0, 1.0])

```
WARNING: slice is deprecated, use view instead.
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in slice(::Array{Float64,2}, ::Vararg{Any,N}) at ./deprecated.jl:30
 in sumabs2j at /home/jmarcellopereira/.julia/v0.5/NLsolve/src/utils.jl:1 [inlined]
 in trust_region_(::NLsolve.DifferentiableMultivariateFunction, ::Array{Float64,1}, ::Float64, ::Float64, ::Int64, ::Bool, ::Bool, ::Bool, ::Float64, ::Bool) at /home/jmarcellopereira/.julia/v0.5/NLsolve/src/trust_region.jl:105
 in #nlsolve#17(::Symbol, ::Float64, ::Float64, ::Int64, ::Bool, ::Bool, ::Bool, ::Function, ::Float64, ::Bool, ::NLsolve.#nlsolve, ::NLsolve.DifferentiableMultivariateFunction, ::Array{Float64,1}) at /home/jmarcellopereira/.julia/v0.5/NLsolve/src/nlsolve_func_defs.jl:24
 in (::NLsolve.#kw##nlsolve)(::Array{Any,1}, ::NLsolve.#nlsolve, ::NLsolve.DifferentiableMultivariateFunction, ::Array{Float64,1}) at ./<missing>:0
 in #nlsolve#19(::Symbol, ::Float64, ::Float64, ::Int64, ::Bool, ::Bool, ::Bool, ::Function, ::Float64, ::Bool, ::Bool, ::NLsolve.#nlsolve, ::#sistema_NLS, ::Array{Float64,1}) at /home/jmarcellopereira/.julia/v0.5/NLsolve/src/nlsolve_func_defs.jl:70
 in nlsolve(::Function, ::Array{Float64,1}) at /home/jmarcellopereira/.julia/v0.5/NLsolve/src/nlsolve_func_defs.jl:65
 in include_string(::String, ::String) at ./loading.jl:441
 in execute_request(::ZMQ.Socket, ::IJulia.Msg) at /home/jmarcellopereira/.julia/v0.5/IJulia/src/execute_request.jl:169
 in eventloop(::ZMQ.Socket) at /home/jmarcellopereira/.julia/v0.5/IJulia/src/eventloop.jl:8
 in (::IJulia.##9#15)() at ./task.jl:360
while loading In[3], in expression starting on line 1
WARNING: slice is deprecated, use view instead.
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in slice(::Array{Float64,2}, ::Vararg{Any,N}) at ./deprecated.jl:30
 in sumabs2j at /home/jmarcellopereira/.julia/v0.5/NLsolve/src/utils.jl:1 [inlined]
 in trust_region_(::NLsolve.DifferentiableMultivariateFunction, ::Array{Float64,1}, ::Float64, ::Float64, ::Int64, ::Bool, ::Bool, ::Bool, ::Float64, ::Bool) at /home/jmarcellopereira/.julia/v0.5/NLsolve/src/trust_region.jl:145
 in #nlsolve#17(::Symbol, ::Float64, ::Float64, ::Int64, ::Bool, ::Bool, ::Bool, ::Function, ::Float64, ::Bool, ::NLsolve.#nlsolve, ::NLsolve.DifferentiableMultivariateFunction, ::Array{Float64,1}) at /home/jmarcellopereira/.julia/v0.5/NLsolve/src/nlsolve_func_defs.jl:24
 in (::NLsolve.#kw##nlsolve)(::Array{Any,1}, ::NLsolve.#nlsolve, ::NLsolve.DifferentiableMultivariateFunction, ::Array{Float64,1}) at ./<missing>:0
 in #nlsolve#19(::Symbol, ::Float64, ::Float64, ::Int64, ::Bool, ::Bool, ::Bool, ::Function, ::Float64, ::Bool, ::Bool, ::NLsolve.#nlsolve, ::#sistema_NLS, ::Array{Float64,1}) at /home/jmarcellopereira/.julia/v0.5/NLsolve/src/nlsolve_func_defs.jl:70
 in nlsolve(::Function, ::Array{Float64,1}) at /home/jmarcellopereira/.julia/v0.5/NLsolve/src/nlsolve_func_defs.jl:65
 in include_string(::String, ::String) at ./loading.jl:441
 in execute_request(::ZMQ.Socket, ::IJulia.Msg) at /home/jmarcellopereira/.julia/v0.5/IJulia/src/execute_request.jl:169
 in eventloop(::ZMQ.Socket) at /home/jmarcellopereira/.julia/v0.5/IJulia/src/eventloop.jl:8
 in (::IJulia.##9#15)() at ./task.jl:360
while loading In[3], in expression starting on line 1

**Comment by ChrisRackauckas** [comment]
This is fixed on master which just needs a tag.

**Comment by KristofferC** [comment]
Taggeed
