### ISSUE TITLE
Adding additional parameter support

### ISSUE THREAD

**Issue by dehann** [EconForge/NLsolve.jl#77]
Hi, thanks for putting this package out there! I've been using this more and more in [IncrementalInference.jl](https://github.com/dehann/IncrementalInference.jl). My use case suffers a large performance penalty for a rather trivial reason. I am frequently generating new function handles (lambdas) during general solving. The performance hit comes each time I have to generate a new lambda function. The first run requires type inference inside Julia itself, which in turn invokes a mass of code and resources each time.

I can avoid this problem by generating the lambdas less frequently, but would require NLsolve to allow me pass additional parameters through to my residual functions. Currently I'm forced to repeatedly do
```julia
f! = (x, res) -> somefnc(x,res,...).
```
Would something like this be possible:
```julia
function f2!(x, res, p1,p2)
  @show p1,p2
  # compute with variables
  res[:] = zeros(length(res))
  nothing
end

NLsolve.nlsolve(f!, init, params1, params2)
```
I tried the following and multiple dispatch seems to do fine with (testing on Julia v0.5):
```julia
function nlsolve{T}(f!::Function,
           g!::Function,
           initial_x::Vector{T},
           params...;
           method::Symbol = :trust_region)
  #
  f!(initial_x, ones(2), params...)
end

nlsolve(f2!, +, ones(2), 2.0, 3.0)
nlsolve(f2!, +, ones(2), 4.0, 5.0,method=:newton)
nlsolve(f2!, +, ones(2), :foo, "bar")

# for reference and compatibility
function f0!(x, res)
  @show x
  res[:] = zeros(length(res))
  nothing
end

nlsolve(f0!, +, ones(2))
nlsolve(f0!, +, -1*ones(2),method=:newton)
```
This will change  ```function nlsolve{T}(...)``` lines of src/nlsolve_func_defs.jl, and all the places where the function is called in ```:newton``` and ```:trust_region``` cases.

Is anyone else interested in such an ability and/or not in favor of such a change?

Thanks

**Comment by ChrisRackauckas** [comment]
What about using call overloading like this?

https://github.com/JuliaDiffEq/ParameterizedFunctions.jl#manually-defining-parameterizedfunctions

```julia
type  LotkaVolterra <: ParameterizedFunction
         a::Float64
         b::Float64
end
f = LotkaVolterra(0.0,0.0)
(p::LotkaVolterra)(t,u,du) = begin
         du[1] = p.a * u[1] - p.b * u[1]*u[2]
         du[2] = -3 * u[2] + u[1]*u[2]
end
```

**Comment by dehann** [comment]
That could work, but I'd have to go check in more detail regarding generating new types every time. I would have to generate many unique type names at each instance. Maybe there is a way to wrap a user function with a ```ParameterizedFunction``` similar to your suggestion, but would only require a single type definition for many different functions -- many variations beyond ```.a``` and ```.b```. Maybe something like (I'm guessing now):
```julia
type WrapParams <: ParameterizedFunction
   params::Tuple
end

f = WrapParams((:foo,"bar",[1.0]))
```
I'd have to spend a bit more time with your syntax to understand how dispatch is going to handle the generation and inference of many different calls. I'm scared this might still invoke the large type inference calls regularly. Although I'm pretty confident I can get around my first major performance hit by being able to pass parameters directly through. I'd still have to generate lambdas at some frequency.

**Comment by ChrisRackauckas** [comment]
You don't need to use an actual `ParameterizedFunction`, that's a JuliaDiffEq thing. But you can just do

```julia
type WrapParams <: Function
```

and it should work with most packages which expect a function. You can make a type per parameter setup. If you're changing the values of the parameters all the time, this will make it so that way you don't have to generate new types/functions, just change the fields. This only won't work if you have to change what the types of the parameters are very often, or which parameters are available.

But there's no reason to wrap all of the params in a tuple. The way I showed it makes inference happen at compile-time.

**Comment by dehann** [comment]
Okay, let me chew on this a bit and see if I can get it working, thanks!

**Comment by ChrisRackauckas** [comment]
No problem. Let me know if you need any help getting it to work. For reference, the section in the manual for it is here:

http://docs.julialang.org/en/release-0.5/manual/methods/#function-like-objects

I just showed how to use the fields from the type you're overloading.

**Comment by dehann** [comment]
@ChrisRackauckas, thanks -- so these parameterized functions are pretty cool. I found the multiple dispatch performance to be slightly spotty in my specific case. I had a bit of difficulty reproducing a positive and negative example, showing some phantom computation delay which did not show up in ProfileView. However, in the end I got a stable fast implementation working. I think the phantom cases may have some interplay with garbage collection. Sometimes I would see the difference between 0.5s and 4s for an in computation time, but garbage collection of roughly the same size would be called in either case. I'll keep my eye out and create an issue if I can pin it down.

Regardless, here is the type I am going work towards (currently Tuple is broken out separately):
```julia
type WrapParam{T} <: Function
  variables::Tuple
  varidx::Int
  reuse::T
end

fw! = WrapType(..., ReuseType(..))
(p::WrapType{ReuseType})(x::Vector{Float64}, res::Vector{Float64}) = somefnc!(res, x, p)
@show fw!(x, res)
```
This actually allows me to refactor the code into a much more general framework. Will share when ready to show.

The switch to parametric functors looks like a 10x improvement in speed, avoiding regular type inference. Then coupled with a easier in place memory component, as shown above, giving about another 10x in my case. So thanks, a 100x improvement and better refactoring is a fun outcome! Thanks for the help.

**Comment by ChrisRackauckas** [comment]
```julia
type WrapParam{T} <: Function
  variables::Tuple
  varidx::Int
  reuse::T
end
```

Note that `Tuple` is an abstract type, so you may want to more strictly type that 

```julia
type WrapParam{T,T2} <: Function
  variables::T2
  varidx::Int
  reuse::T
end
```

for better performance. But I'm glad it worked out!

**Comment by KristofferC** [comment]
A closure is pretty much exactly like a type that has been "call"-overloaded. You can even access its fields. There is also no compilation cost for creating closures when the parameters that are closed over changes.

```jl
julia> function f(x)
          g(y) = x+y
          println(g.x) # Access field
          return g(25)
       end
f (generic function with 1 method)

julia> @time f(33)
33
  0.031454 seconds (8.69 k allocations: 414.794 KB)
58

julia> @time f(32) # No compilation cost on second call even with changing argument
32
  0.000030 seconds (10 allocations: 752 bytes)
57
```

I am surprised you see a speedup from changing to a type + call overload. It shouldn't really be necessary.

**Comment by ChrisRackauckas** [comment]
>A closure is pretty much exactly like a type that has been "call"-overloaded.

I am pretty sure it's actually the same thing. An anonymous function / closure just does `gensym` to create a new type, adds the fields, and overloads the call. If I was understanding his problem correctly, it's that his current setup had him creating a bunch of anonymous functions / closures, whereas he could've just been changing parameters which is where the speedup comes from. 

I actually never knew you could change the fields of a closure, but I think explicitly making the type and overloading the call can lead to a much easier to understand structure and is easier to document.

**Comment by dehann** [comment]
Maybe some background on what I'm doing might help. I'm using NLsolve to numerically approximate a convolution operation. I'm *transiting* belief of one variable through some user defined non-linear function to a new dimension. Enforcing a conditional belief:
```
p(z | w, x, y)
```
I'm building on top of Graphs.jl to do this with a graphical model interface. I'd like to have an interface to the user which goes approximately something like this,
```julia
# note x and y are vectorized, and of different dimensions
type myconstr    #  future option <: Function
  z::#could really be anything the user wants, images, gaussians, kde's, etc
  ...
end
# previous solution requires the user to implement something close to this
function residual!(resid::Vector{Float64}, data::myconstr, w,x,y)
  resid[:] = data.z \ominus h(w,x,y) # just as example, but could be anything
  nothing
end

addnode!(g,:w,...)
addnode!(g,:x,...)
addnode!(g,:y,...)
addfactor(g, [:w,:x,:y], myconstr(somedata) )
...
solve(g)
```
I would then internally, somewhere during computation, require the conditional to be enforced to say just ```:x```, or ```:y```. To do this I use NLsolve to root find on the user residual function and solve for one variable relative to the others. The result is many internal lambda incarnations---then also being passed amongst several functions---to ultimately fit the ```(x, res)``` interface of NLsolve.
```julia
ff = (x, res) -> residual!(res, DATA, WW, XX, x) # or elsewhere
ff = (x, res) -> residual!(res, DATA, x, YY, ZZ)
```
The issue has been getting some combination of ```XX, YY, ZZ```, which is only available at runtime, passed to the user through a callback ```::Function``` or multiple dispatch, as in this example. 

Since talking with with you guys here, I think functors, as workhorse of closures, is probably the right way to go in the future
```julia
type Betterconstr{USERTYPE} <: Function
  params::Tuple
  varidx::Int
  z::USERTYPE
end

# hand-waivy internal usage
function (data::Betterconstr)(x, res)
  data.param[varidx] = x
  residual!(res, data.z, data.params...)
  nothing
end
...
newfnc = Betterconstr{typeof(getfactor(g, <function between :xyz>))}(...)
...
newfnc.params = getval(g, :x), getval(g, :y), getval(g, :z)
newfnc.varidx  = 2 # in reality root finding to solve for :y
...
newvalfory = nlsolve(newfnc, getval(g, :y)).zero # using numerical gradient
```
Hence the low restriction on ```params::Tuple```.

Current incarnation actually seems to work, but many improvements are needed ... [video](https://vimeo.com/190052649)
